Implementing & covering option `streamSizeLimit`.
Wandalen/wProcess pull request #116
Opened 2020-10-20 11:48 UTC by JackieJoo

1. Implementing & covering option `streamSizeLimit`.
    streamSizeLimit : null, /* qqq for Yevhen : implement and cover the option. look option maxBuffer of spawn */

2020-10-22 05:52 UTC, Wandalen requested changes

2020-10-22 05:52 UTC, Wandalen commented on proto/wtools/abase/l4_process/l3/Execution.s
> +  _.assert( o.sync && ( o.mode === 'spawn' || o.mode === 'shell' ), 'Option::streamSizeLimit is allowed in mode::spawn and mode::shell with sync::1' )
is allowed -> is supported

2020-10-22 05:52 UTC, Wandalen commented on proto/wtools/abase/l4_process/l3/Execution.s
> +    ( _.numberIs( o.streamSizeLimit ) && o.streamSizeLimit >= 0 ) || o.streamSizeLimit === null, 'Option::streamSizeLimit must be a positive Number which is greater or equal to zero'
too long line

2020-10-22 05:52 UTC, Wandalen commented on proto/wtools/abase/l4_process/l3/Execution.s
> +    o2.maxBuffer = o.streamSizeLimit ? o.streamSizeLimit : 1024 * 1024;
dont redefine maxBuffer if streamSizeLimit is null

2020-10-22 05:52 UTC, Wandalen commented on proto/wtools/abase/l4_process/l3/Execution.s
> +    o2.maxBuffer = o.streamSizeLimit ? o.streamSizeLimit : 1024 * 1024;
dont redefine maxBuffer if streamSizeLimit is null

2020-10-22 05:52 UTC, Wandalen commented on proto/wtools/abase/l4_process/l3/Execution.s
> +    ( _.numberIs( o.streamSizeLimit ) && o.streamSizeLimit >= 0 ) || o.streamSizeLimit === null, 'Option::streamSizeLimit must be a positive Number which is greater or equal to zero'
greater than zero!

2020-10-22 05:52 UTC, Wandalen commented on proto/wtools/abase/l4_process/l3/Execution.s
> +  _.assert( o.sync && ( o.mode === 'spawn' || o.mode === 'shell' ), 'Option::streamSizeLimit is allowed in mode::spawn and mode::shell with sync::1' )
assert should be covered! where is coverage?

2020-10-22 07:59 UTC, JackieJoo commented on proto/wtools/abase/l4_process/l3/Execution.s
> +    o2.maxBuffer = o.streamSizeLimit ? o.streamSizeLimit : 1024 * 1024;
Done

2020-10-22 08:00 UTC, JackieJoo commented on proto/wtools/abase/l4_process/l3/Execution.s
> +    o2.maxBuffer = o.streamSizeLimit ? o.streamSizeLimit : 1024 * 1024;
Removed adding `maxBuffer` in routine `optionsForFork`. mode::fork doesn't support `maxBuffer`.

2020-10-22 08:06 UTC, JackieJoo commented on proto/wtools/abase/l4_process/l3/Execution.s
> +    ( _.numberIs( o.streamSizeLimit ) && o.streamSizeLimit >= 0 ) || o.streamSizeLimit === null, 'Option::streamSizeLimit must be a positive Number which is greater or equal to zero'
Refactored.

2020-10-22 08:06 UTC, JackieJoo commented on proto/wtools/abase/l4_process/l3/Execution.s
> +  _.assert( o.sync && ( o.mode === 'spawn' || o.mode === 'shell' ), 'Option::streamSizeLimit is allowed in mode::spawn and mode::shell with sync::1' )
Renamed.
All asserts are already covered in the test routine `startOptionStreamSizeLimitThrowing`.

2020-10-22 15:47 UTC, Wandalen commented on proto/wtools/abase/l4_process/l3/Execution.s
> +  _.assert( o.sync && ( o.mode === 'spawn' || o.mode === 'shell' ), 'Option::streamSizeLimit is supported in mode::spawn and mode::shell with sync::1' )
too long line!

2020-10-22 20:23 UTC, JackieJoo commented on proto/wtools/abase/l4_process/l3/Execution.s
> +  _.assert( o.sync && ( o.mode === 'spawn' || o.mode === 'shell' ), 'Option::streamSizeLimit is supported in mode::spawn and mode::shell with sync::1' )
Fixed

2020-10-26 15:43 UTC, Wandalen commented on proto/wtools/abase/l4_process/l3/Execution.s
> +    o2.maxBuffer = o.streamSizeLimit ? o.streamSizeLimit : 1024 * 1024;
No!

2020-10-26 15:48 UTC, Wandalen commented
no loossy conditions

2020-10-26 16:01 UTC, merged